using Microsoft.EntityFrameworkCore.Migrations;

namespace Catalog.Persistence.Migrations
{
    public partial class Initial : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CommodityTypes",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommodityTypes", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Commodities",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Description = table.Column<string>(nullable: false),
                    ImageUrl = table.Column<string>(nullable: false),
                    Price = table.Column<decimal>(nullable: false),
                    Currency = table.Column<string>(nullable: false),
                    Amount = table.Column<int>(nullable: false),
                    CommodityTypeId = table.Column<int>(nullable: false),
                    SalePrice = table.Column<decimal>(nullable: true),
                    OnSale = table.Column<bool>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Commodities", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Commodities_CommodityTypes_CommodityTypeId",
                        column: x => x.CommodityTypeId,
                        principalTable: "CommodityTypes",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "CommodityTypes",
                columns: new[] { "Id", "Name" },
                values: new object[,]
                {
                    { 1, "Automotive" },
                    { 2, "Kids" },
                    { 3, "Sports" },
                    { 4, "Industrial" },
                    { 5, "Jewelery" }
                });

            migrationBuilder.InsertData(
                table: "Commodities",
                columns: new[] { "Id", "Amount", "CommodityTypeId", "Currency", "Description", "ImageUrl", "OnSale", "Price", "SalePrice" },
                values: new object[,]
                {
                    { 1, 1405, 1, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=76", false, 180.85m, null },
                    { 159, 462, 4, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=531", false, 85.60m, null },
                    { 160, 1539, 4, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=61", false, 349.66m, null },
                    { 161, 1126, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=642", false, 952.52m, null },
                    { 162, 1005, 4, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=968", false, 390.26m, null },
                    { 163, 29, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=974", false, 817.50m, null },
                    { 164, 854, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=404", false, 238.68m, null },
                    { 165, 128, 4, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=209", false, 93.00m, null },
                    { 166, 1378, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=88", false, 864.92m, null },
                    { 167, 562, 4, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=282", false, 845.64m, null },
                    { 168, 1636, 4, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=571", false, 172.88m, null },
                    { 169, 605, 4, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=76", false, 583.64m, null },
                    { 170, 1160, 4, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=186", false, 22.85m, null },
                    { 171, 49, 4, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=188", false, 587.99m, null },
                    { 172, 96, 4, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=406", false, 269.96m, null },
                    { 173, 1424, 4, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=797", false, 426.22m, null },
                    { 174, 1334, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=764", false, 367.75m, null },
                    { 175, 485, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=740", false, 311.39m, null },
                    { 176, 1364, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=92", false, 75.53m, null },
                    { 177, 1959, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=1019", false, 596.07m, null },
                    { 178, 546, 4, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=585", false, 793.08m, null },
                    { 179, 25, 4, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=561", false, 169.41m, null },
                    { 180, 542, 4, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=708", false, 34.25m, null },
                    { 181, 1101, 4, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=114", false, 549.10m, null },
                    { 182, 1008, 4, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=159", false, 860.28m, null },
                    { 183, 241, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=769", false, 828.28m, null },
                    { 184, 428, 4, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=971", false, 490.45m, null },
                    { 185, 193, 4, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=822", false, 195.04m, null },
                    { 158, 650, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=755", false, 526.58m, null },
                    { 186, 64, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=590", false, 102.72m, null },
                    { 157, 1398, 4, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=653", false, 64.59m, null },
                    { 155, 572, 4, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=158", false, 544.51m, null },
                    { 128, 1546, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=268", false, 381.14m, null },
                    { 129, 1598, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=205", false, 216.96m, null },
                    { 130, 1090, 3, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=985", false, 781.34m, null },
                    { 131, 467, 3, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=279", false, 407.28m, null },
                    { 132, 654, 3, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=698", false, 430.18m, null },
                    { 133, 1157, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=982", false, 522.62m, null },
                    { 134, 1631, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=991", false, 202.09m, null },
                    { 135, 351, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=393", false, 526.15m, null },
                    { 136, 1880, 3, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=187", false, 324.83m, null },
                    { 137, 1784, 3, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=109", false, 697.63m, null },
                    { 138, 187, 3, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=540", false, 611.31m, null },
                    { 139, 1216, 3, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=198", false, 883.24m, null },
                    { 140, 620, 3, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=98", false, 892.25m, null },
                    { 141, 540, 3, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=383", false, 608.50m, null },
                    { 142, 341, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=560", false, 432.43m, null },
                    { 143, 1084, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=931", false, 15.00m, null },
                    { 144, 73, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=82", false, 969.05m, null },
                    { 145, 1335, 3, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=1073", false, 366.39m, null },
                    { 146, 1343, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=1037", false, 550.46m, null },
                    { 147, 1618, 3, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=975", false, 297.95m, null },
                    { 148, 799, 3, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=650", false, 604.06m, null },
                    { 149, 1589, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=112", false, 93.92m, null },
                    { 150, 1099, 3, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=451", false, 3.55m, null },
                    { 151, 1811, 4, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=858", false, 559.37m, null },
                    { 152, 1215, 4, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=205", false, 461.66m, null },
                    { 153, 1894, 4, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=82", false, 516.31m, null },
                    { 154, 420, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=1021", false, 420.45m, null },
                    { 156, 356, 4, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=568", false, 117.59m, null },
                    { 187, 1839, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=809", false, 722.08m, null },
                    { 188, 1975, 4, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=598", false, 433.52m, null },
                    { 189, 1676, 4, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=228", false, 133.26m, null },
                    { 222, 1487, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=711", false, 901.33m, null },
                    { 223, 1459, 5, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=686", false, 87.39m, null },
                    { 224, 1380, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=13", false, 964.06m, null },
                    { 225, 1388, 5, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=277", false, 92.30m, null },
                    { 226, 1921, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=723", false, 55.92m, null },
                    { 227, 985, 5, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=643", false, 260.52m, null },
                    { 228, 605, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=443", false, 542.50m, null },
                    { 229, 899, 5, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=1009", false, 189.23m, null },
                    { 230, 381, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=497", false, 255.85m, null },
                    { 231, 559, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=691", false, 701.74m, null },
                    { 232, 145, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=1082", false, 154.71m, null },
                    { 233, 404, 5, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=789", false, 210.99m, null },
                    { 234, 161, 5, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=35", false, 260.51m, null },
                    { 235, 1665, 5, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=318", false, 443.90m, null },
                    { 236, 969, 5, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=11", false, 353.26m, null },
                    { 237, 1451, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=167", false, 184.09m, null },
                    { 238, 1037, 5, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=15", false, 821.95m, null },
                    { 239, 533, 5, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=908", false, 975.97m, null },
                    { 240, 427, 5, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=658", false, 594.38m, null },
                    { 241, 593, 5, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=515", false, 391.85m, null },
                    { 242, 1016, 5, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=1075", false, 328.45m, null },
                    { 243, 551, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=909", false, 98.87m, null },
                    { 244, 471, 5, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=1054", false, 974.15m, null },
                    { 245, 1540, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=428", false, 912.12m, null },
                    { 246, 1405, 5, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=182", false, 479.46m, null },
                    { 247, 12, 5, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=486", false, 461.42m, null },
                    { 248, 966, 5, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=449", false, 818.93m, null },
                    { 221, 1895, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=1015", false, 20.12m, null },
                    { 220, 498, 5, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=238", false, 715.01m, null },
                    { 219, 1409, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=980", false, 840.43m, null },
                    { 218, 1809, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=915", false, 519.40m, null },
                    { 190, 1161, 4, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=588", false, 581.19m, null },
                    { 191, 860, 4, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=427", false, 818.67m, null },
                    { 192, 678, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=731", false, 326.46m, null },
                    { 193, 861, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=833", false, 421.42m, null },
                    { 194, 994, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=239", false, 621.40m, null },
                    { 195, 738, 4, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=670", false, 187.47m, null },
                    { 196, 1431, 4, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=294", false, 160.42m, null },
                    { 197, 892, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=603", false, 871.34m, null },
                    { 198, 413, 4, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=138", false, 315.49m, null },
                    { 199, 1844, 4, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=632", false, 328.60m, null },
                    { 200, 1023, 4, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=906", false, 206.31m, null },
                    { 201, 1120, 5, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=774", false, 316.74m, null },
                    { 202, 857, 5, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=610", false, 55.46m, null },
                    { 127, 919, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=202", false, 480.19m, null },
                    { 203, 72, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=625", false, 842.27m, null },
                    { 205, 578, 5, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=67", false, 948.03m, null },
                    { 206, 425, 5, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=164", false, 467.54m, null },
                    { 207, 1917, 5, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=916", false, 846.85m, null },
                    { 208, 1895, 5, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=717", false, 709.08m, null },
                    { 209, 1597, 5, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=724", false, 59.08m, null },
                    { 210, 1595, 5, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=848", false, 842.84m, null },
                    { 211, 444, 5, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=319", false, 520.75m, null },
                    { 212, 874, 5, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=1040", false, 346.32m, null },
                    { 213, 1652, 5, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=1046", false, 294.73m, null },
                    { 214, 1520, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=858", false, 622.71m, null },
                    { 215, 1162, 5, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=147", false, 755.91m, null },
                    { 216, 1636, 5, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=1083", false, 615.44m, null },
                    { 217, 406, 5, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=467", false, 778.19m, null },
                    { 204, 1565, 5, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=343", false, 826.73m, null },
                    { 126, 349, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=237", false, 833.24m, null },
                    { 125, 120, 3, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=126", false, 824.92m, null },
                    { 124, 1690, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=168", false, 811.27m, null },
                    { 34, 543, 1, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=31", false, 101.49m, null },
                    { 35, 188, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=354", false, 474.15m, null },
                    { 36, 747, 1, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=546", false, 221.80m, null },
                    { 37, 37, 1, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=380", false, 628.75m, null },
                    { 38, 1930, 1, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=9", false, 973.96m, null },
                    { 39, 1894, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=309", false, 956.74m, null },
                    { 40, 231, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=27", false, 695.52m, null },
                    { 41, 414, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=791", false, 660.93m, null },
                    { 42, 718, 1, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=136", false, 610.95m, null },
                    { 43, 1982, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=437", false, 526.51m, null },
                    { 44, 1708, 1, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=742", false, 878.81m, null },
                    { 45, 993, 1, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=18", false, 85.77m, null },
                    { 46, 1814, 1, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=556", false, 999.09m, null },
                    { 47, 253, 1, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=657", false, 765.66m, null },
                    { 48, 603, 1, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=699", false, 912.98m, null },
                    { 49, 907, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=261", false, 120.60m, null },
                    { 50, 1778, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=770", false, 145.50m, null },
                    { 51, 726, 2, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=943", false, 359.88m, null },
                    { 52, 452, 2, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=1069", false, 155.34m, null },
                    { 53, 1575, 2, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=596", false, 789.15m, null },
                    { 54, 728, 2, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=893", false, 119.83m, null },
                    { 55, 266, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=6", false, 603.04m, null },
                    { 56, 1087, 2, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=190", false, 824.37m, null },
                    { 57, 365, 2, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=440", false, 949.67m, null },
                    { 58, 1683, 2, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=5", false, 795.74m, null },
                    { 59, 844, 2, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=438", false, 654.04m, null },
                    { 60, 47, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=603", false, 287.54m, null },
                    { 33, 531, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=772", false, 362.61m, null },
                    { 32, 1981, 1, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=1045", false, 733.56m, null },
                    { 31, 467, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=112", false, 71.31m, null },
                    { 30, 1105, 1, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=273", false, 288.32m, null },
                    { 2, 72, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=545", false, 753.37m, null },
                    { 3, 1874, 1, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=301", false, 748.47m, null },
                    { 4, 1879, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=424", false, 774.66m, null },
                    { 5, 1625, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=586", false, 277.63m, null },
                    { 6, 791, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=377", false, 829.84m, null },
                    { 7, 1752, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=397", false, 343.07m, null },
                    { 8, 283, 1, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=42", false, 619.45m, null },
                    { 9, 1017, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=1007", false, 7.85m, null },
                    { 10, 1689, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=693", false, 429.07m, null },
                    { 11, 1827, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=694", false, 789.07m, null },
                    { 12, 1799, 1, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=754", false, 482.18m, null },
                    { 13, 1064, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=161", false, 116.26m, null },
                    { 14, 1128, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=1049", false, 419.66m, null },
                    { 61, 398, 2, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=31", false, 819.04m, null },
                    { 15, 144, 1, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=368", false, 196.03m, null },
                    { 17, 1444, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=320", false, 769.09m, null },
                    { 18, 286, 1, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=189", false, 547.52m, null },
                    { 19, 105, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=757", false, 627.42m, null },
                    { 20, 1893, 1, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=112", false, 449.02m, null },
                    { 21, 430, 1, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=36", false, 834.65m, null },
                    { 22, 534, 1, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=55", false, 475.89m, null },
                    { 23, 450, 1, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=13", false, 856.12m, null },
                    { 24, 884, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=571", false, 373.03m, null },
                    { 25, 672, 1, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=206", false, 918.04m, null },
                    { 26, 6, 1, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=743", false, 553.02m, null },
                    { 27, 1121, 1, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=1004", false, 97.26m, null },
                    { 28, 1661, 1, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=957", false, 21.82m, null },
                    { 29, 767, 1, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=672", false, 125.18m, null },
                    { 16, 533, 1, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=601", false, 362.24m, null },
                    { 249, 1517, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=241", false, 996.96m, null },
                    { 62, 52, 2, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=841", false, 281.71m, null },
                    { 64, 1778, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=388", false, 167.56m, null },
                    { 97, 1156, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=123", false, 466.38m, null },
                    { 98, 666, 2, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=437", false, 797.92m, null },
                    { 99, 1677, 2, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=230", false, 883.06m, null },
                    { 100, 1084, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=505", false, 530.96m, null },
                    { 101, 403, 3, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=823", false, 291.68m, null },
                    { 102, 932, 3, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=930", false, 486.92m, null },
                    { 103, 1762, 3, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=579", false, 497.93m, null },
                    { 104, 827, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=606", false, 383.93m, null },
                    { 105, 476, 3, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=197", false, 398.99m, null },
                    { 106, 381, 3, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=101", false, 793.29m, null },
                    { 107, 1279, 3, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=38", false, 371.59m, null },
                    { 108, 619, 3, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=998", false, 852.30m, null },
                    { 109, 891, 3, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=512", false, 946.68m, null },
                    { 110, 1388, 3, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=9", false, 156.99m, null },
                    { 111, 1213, 3, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=165", false, 233.64m, null },
                    { 112, 1388, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=393", false, 989.29m, null },
                    { 113, 260, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=469", false, 973.93m, null },
                    { 114, 1152, 3, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=731", false, 275.97m, null },
                    { 115, 1776, 3, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=918", false, 120.40m, null },
                    { 116, 396, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=915", false, 548.31m, null },
                    { 117, 656, 3, "UAH", "The Football Is Good For Training And Recreational Purposes", "https://picsum.photos/640/480/?image=295", false, 89.55m, null },
                    { 118, 1059, 3, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=297", false, 864.79m, null },
                    { 119, 1907, 3, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=632", false, 576.08m, null },
                    { 120, 588, 3, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=408", false, 399.70m, null },
                    { 121, 1261, 3, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=1069", false, 905.75m, null },
                    { 122, 125, 3, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=105", false, 344.77m, null },
                    { 123, 1732, 3, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=538", false, 584.82m, null },
                    { 96, 305, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=675", false, 723.36m, null },
                    { 95, 1789, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=160", false, 607.50m, null },
                    { 94, 1099, 2, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=427", false, 249.69m, null },
                    { 93, 569, 2, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=227", false, 23.63m, null },
                    { 65, 1357, 2, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=374", false, 686.98m, null },
                    { 66, 1242, 2, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=162", false, 145.42m, null },
                    { 67, 954, 2, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=1073", false, 128.32m, null },
                    { 68, 49, 2, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=3", false, 800.29m, null },
                    { 69, 1722, 2, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=828", false, 806.76m, null },
                    { 70, 371, 2, "UAH", "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart", "https://picsum.photos/640/480/?image=888", false, 150.58m, null },
                    { 71, 1200, 2, "UAH", "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016", "https://picsum.photos/640/480/?image=591", false, 77.55m, null },
                    { 72, 1061, 2, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=306", false, 117.01m, null },
                    { 73, 416, 2, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=911", false, 725.51m, null },
                    { 74, 886, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=488", false, 935.40m, null },
                    { 75, 1270, 2, "UAH", "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles", "https://picsum.photos/640/480/?image=262", false, 552.60m, null },
                    { 76, 472, 2, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=666", false, 750.70m, null },
                    { 77, 991, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=914", false, 880.72m, null }
                });

            migrationBuilder.InsertData(
                table: "Commodities",
                columns: new[] { "Id", "Amount", "CommodityTypeId", "Currency", "Description", "ImageUrl", "OnSale", "Price", "SalePrice" },
                values: new object[,]
                {
                    { 63, 658, 2, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=804", false, 108.39m, null },
                    { 78, 665, 2, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=958", false, 173.58m, null },
                    { 80, 1344, 2, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=458", false, 619.49m, null },
                    { 81, 1336, 2, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=791", false, 781.41m, null },
                    { 82, 1980, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=997", false, 560.89m, null },
                    { 83, 222, 2, "UAH", "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design", "https://picsum.photos/640/480/?image=560", false, 129.43m, null },
                    { 84, 486, 2, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=334", false, 583.41m, null },
                    { 85, 848, 2, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=462", false, 50.62m, null },
                    { 86, 347, 2, "UAH", "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality", "https://picsum.photos/640/480/?image=873", false, 950.49m, null },
                    { 87, 245, 2, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=624", false, 807.04m, null },
                    { 88, 392, 2, "UAH", "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J", "https://picsum.photos/640/480/?image=38", false, 778.54m, null },
                    { 89, 100, 2, "UAH", "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive", "https://picsum.photos/640/480/?image=424", false, 574.87m, null },
                    { 90, 1021, 2, "UAH", "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support", "https://picsum.photos/640/480/?image=581", false, 624.49m, null },
                    { 91, 1087, 2, "UAH", "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals", "https://picsum.photos/640/480/?image=1059", false, 731.79m, null },
                    { 92, 549, 2, "UAH", "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit", "https://picsum.photos/640/480/?image=136", false, 640.74m, null },
                    { 79, 67, 2, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=484", false, 745.64m, null },
                    { 250, 1833, 5, "UAH", "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients", "https://picsum.photos/640/480/?image=987", false, 503.16m, null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Commodities_CommodityTypeId",
                table: "Commodities",
                column: "CommodityTypeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Commodities");

            migrationBuilder.DropTable(
                name: "CommodityTypes");
        }
    }
}
